const mongoose = require('mongoose');

//Schema
const { Schema } = mongoose;
const ownTweetsSchema = new Schema({
    category: String,
    tweet: {
        created_at: Date,
        id: Number,
        id_str: String,
        text: String,
        source: String,
        truncated: Boolean,
        in_reply_to_status_id: Number,
        in_reply_to_status_id_str: String,
        in_reply_to_user_id: Number,
        in_reply_to_user_id_str: String,
        in_reply_to_screen_name: String,
        user: {
          id: Number,
          id_str: String,
          name: String,
          screen_name: String,
          location: String,
          description: String,
          followers_count: Number,
          friends_count: Number,
          listed_count: Number,
          statuses_count: Number,
          created_at: Date,
          verified: Boolean,
        },
        coordinates: Object,
        place: Object,
        quoted_status_id: Number,
        quoted_status_id_str: String,
        is_quote_status: Boolean,
        quoted_status: Object,
        retweeted_status: Object,
        quote_count: Number,
        reply_count: Number,
        retweet_count: Number,
        favorite_count: Number,
        entities: Object,
        extended_entities: Object,
        favorited: Boolean,
        retweeted: Boolean,
        possibly_sensitive: Boolean,
        filter_level: String,
        lang: String,
        matching_rules: Array,
    },
  });

module.exports = { ownTweetsSchema };